{% set name = "flask-swagger-ui" %}
{% set version = "5.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 872d038dc11a68eacab88f6f05be3c533aa300453e273775dad3e029b31e03d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - flask
    - python >={{ python_min }}

test:
  imports:
    - flask_swagger_ui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sveint/flask-swagger-ui
  summary: Swagger UI blueprint for Flask
  license: MIT
  license_file: flask_swagger_ui/LICENSE

extra:
  recipe-maintainers:
    - xhochy
